# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

stages:
  - functional test

compile_test:
  stage: functional test
  script:
    - npm install
    - npm run compile
  artifacts:
    reports:
      paths:
        - mycv.pdf
      expire_in: 1 week
